### ISSUE TITLE
没有音频啊

### ISSUE THREAD

**Issue by hbtech-ai** [onlyet/ScreenCapture#1]
//vCurPts = pkt.pts; 这句取消注释后，视频的帧率就有问题，期待回复

**Comment by onlyet** [comment]
@hbtech-ai 你好，我这个录屏功能还没有调通，单录视频或音频可以参考其它两个项目。最近有空会继续完成的。

**Comment by hbtech-ai** [comment]
fps设置30帧的时候，音视频不同步，设置为15帧的时候，音视频基本同步，不知道您是怎么解决的。

**Comment by onlyet** [comment]
@hbtech-ai 同步不同步看的是复用的时候pts,timebase的设置吧，你用的是我最新的代码吗，还是之前的？

**Comment by hbtech-ai** [comment]
@onlyet 是最新的，你的环境是音视频是同步的吗

**Comment by onlyet** [comment]
@hbtech-ai 我没有太注意音视频同步，我测试录的都是杂音。。。
