### ISSUE TITLE
使用摄像头录制视频音频不同步

### ISSUE THREAD

**Issue by mixml** [onlyet/ScreenCapture#2]
发现录制视频音频不同步后，尝试使用：
if (av_compare_ts(m_vCurPts, m_vEncodeCtx->time_base,
		                  m_aCurPts, m_aEncodeCtx->time_base) <= 0)对比时间戳的方法进行同步。

其中：m_vCurPts和m_aCurPts在将pts从编码层的timebase转成复用层的timebase前进行赋值操作。

依然出现视频音频不同步的问题。

**Comment by onlyet** [comment]
音视频同步可能是有问题，这个我没有测试过，我没有注意音频，这个我有空再研究一下
