### ISSUE TITLE
Project could not opened with visual studio。

### ISSUE THREAD

**Issue by Tanny802** [onlyet/ScreenCapture#5]
here is the log :
RecordCore\RecordCore.vcxproj : error  : 找不到导入的项目“.\Compressed\ScreenCapture-1-master\RecordCore\QtMsBuild\Qt.props”。请确认 Import 声明“.\Compressed\ScreenCapture-1-master\RecordCore\QtMsBuild\Qt.props”中的表达式正确，且文件位于磁盘上。  .\Compressed\ScreenCapture-1-master\RecordCore\RecordCore.vcxproj

please help to fix it!

**Comment by onlyet** [comment]
I don't meet this problem, try to google it.
